[project]
name = "vlw-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "pywikibot>=10.0.0",
    "wikitextparser>=0.56.4",
]
